### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by aphuang2013** [tkuhlman/gopwsafe#5]
I'm getting compile error here, since I'm not familiar with C integration, how does one deal with clibary import here.

../../go/src/github.com/tkuhlman/gopwsafe/gui/main.go:319:47: undefined: gdk.GDK_CONTROL_MASK
../../go/src/github.com/tkuhlman/gopwsafe/gui/main.go:332:47: undefined: gdk.GDK_CONTROL_MASK

**Comment by tkuhlman** [comment]
This was fixed with https://github.com/tkuhlman/gopwsafe/pull/3
